added new jobs

diff --git a/.github/workflows/class.yml b/.github/workflows/class.yml
--- a/.github/workflows/class.yml
+++ b/.github/workflows/class.yml
@@ -14,19 +14,18 @@ jobs:
         with:
           python-version: '3.12'
 
-      - name: Install dependencies
+      - name: Install pylint
         run: 
           python -m pip install --upgrade pip
-          pip install -r requirements.txt
           pip install pylint
 
-      - name: Run Django tests
+      - name: Run Pylint
         run: 
-          pytest
+          echo "Running Pylint..."
+          pylint **/*.py || true  # Continue even if pylint fails
 
-  lint:
+  test:
     runs-on: ubuntu-latest
-    needs: setup-and-test
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -40,8 +39,20 @@ jobs:
         run: 
           python -m pip install --upgrade pip
           pip install -r requirements.txt
-          pip install pylint
+         
 
-      - name: Run Pylint
+      - name: Run Django tests
         run: 
-          pylint . --ignore=venv,.pytest_cache
+          echo "Running Django tests..."
+          python manage.py test
+
+  deploy:
+    needs: test
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Stimulate deployment
+        run:
+          echo "Deploying application..."
